Clear blackboard data upon puzzle select
uwblueprint/cdc-frontend pull request #86
Opened 2021-06-26 21:18 UTC by amoliksingh

https://www.loom.com/share/063b55cb1d6248f980381a94db9608b9

2021-06-26 22:02 UTC, ahmedhamodi approved these changes

2021-06-28 07:00 UTC, jaydhulia requested changes
Summarized the approach that we should follow on slack, please check that @amoliksingh

2021-06-30 00:12 UTC, jaydhulia approved these changes

2021-06-30 00:24 UTC, ahmedhamodi commented
According to Jay there is a small bug fix needed? Will wait for you to push that up Amolik to re-review

2021-06-30 00:54 UTC, ahmedhamodi approved these changes

2021-06-30 00:59 UTC, merged